name: Build Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'vcf_to_obsidian/**/*.py'
      - 'sphinx/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'vcf_to_obsidian/**/*.py'
      - 'sphinx/**'
      - '.github/workflows/docs.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vobject click
        pip install sphinx sphinx-autoapi sphinx-rtd-theme
        
    - name: Build documentation
      run: |
        cd sphinx
        make clean
        make html
        
    - name: Check documentation build
      run: |
        # Verify that documentation was built successfully
        if [ ! -f "sphinx/build/html/index.html" ]; then
          echo "Error: Documentation build failed - index.html not found"
          exit 1
        fi
        
        # Check for autoapi generated content
        if [ ! -d "sphinx/build/html/autoapi/vcf_to_obsidian" ]; then
          echo "Error: AutoAPI documentation not generated"
          exit 1
        fi
        
        echo "Documentation build successful!"
        ls -la sphinx/build/html/
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: sphinx/build/html/
        retention-days: 30
        
    # Optional: Deploy to GitHub Pages if this is the main branch
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./sphinx/build/html
        force_orphan: true
